import Head from "next/head";
import Image from "next/image";
import { Footer } from "../compornents/Footer";
import { Links } from "../compornents/Links";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About Pages</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/about.js</code>
        </p>

        <Links />
      </main>
      <Footer />
    </div>
  );
}
